name: build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Trivy
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        image:
          - quay.io/k0sproject/apiserver-network-proxy-agent:0.0.33-k0s
          - quay.io/k0sproject/pushgateway-ttl:edge@sha256:7031f6bf6c957e2fdb496161fe3bea0a5bde3de800deeba7b2155187196ecbd9
          - registry.k8s.io/metrics-server/metrics-server:v0.6.2
          - registry.k8s.io/kube-proxy:v1.26.0
          - docker.io/coredns/coredns:1.10.0
          - docker.io/envoyproxy/envoy-distroless:v1.24.1
          - docker.io/calico/cni:v3.24.5
          - docker.io/calico/node
          - docker.io/calico/kube-controllers
          - docker.io/cloudnativelabs/kube-router:v1.5.1
          - quay.io/k0sproject/cni-node:1.1.1-k0s.0
    steps:
      -
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ matrix.image }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
#          vuln-type: 'os,library'
#          severity: 'CRITICAL,HIGH'
